trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Localhost9000'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'spring-petclinic'
    cliSources: '.'
    extraProperties: |
      sonar.projectKey=spring-petclinic

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeAnalysisEnabled: true

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
