trigger:
  branches:
    include:
      - main

pool:
  name: Default    # Your self-hosted agent pool name

variables:
  sonarProjectKey: spring-petclinic
  sonarHostUrl: 'http://localhost:9000'  # Since SonarQube runs locally on your agent machine

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Localhost9000'   # Your SonarQube service connection name in Azure DevOps
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: $(sonarProjectKey)
    cliSources: '.'
    cliOptions: '-Dsonar.host.url=$(sonarHostUrl)'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests'  # Optional: skip tests to speed up build

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
