trigger:
- main

variables:
  dockerRegistryServiceConnection: '850ef9b0-5eeb-4ae2-afb6-df81e99c0ab3'
  imageRepository: 'palakchauhanspringpetclinic'
  containerRegistry: 'palakdevopsregistry.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildAndPush
  displayName: Build, Dockerize, and Push
  jobs:
  - job: BuildAndPushJob
    displayName: Build and Push Docker Image
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: Maven@4  # ✅ Use the latest version of Maven task
      displayName: 'Build Spring Petclinic with Maven'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '-DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.17'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false

    - task: Docker@2
      displayName: 'Build and push Docker image to ACR'
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
