trigger:
- main

variables:
  dockerRegistryServiceConnection: '850ef9b0-5eeb-4ae2-afb6-df81e99c0ab3'
  imageRepository: 'palakchauhanspringpetclinic'
  containerRegistry: 'palakdevopsregistry.azurecr.io'
  dockerfilePath: 'Dockerfile'   # Adjust if your Dockerfile path is different
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildAndPush
  displayName: Build, Dockerize, and Push
  jobs:
  - job: BuildAndPushJob
    displayName: Build and Push Docker Image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Maven@3
      displayName: Build Spring Petclinic with Maven
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        options: '-DskipTests'   # Skip tests to speed up build, remove if you want to run tests

    - task: Docker@2
      displayName: Build and push Docker image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
